### ISSUE TITLE
How to use this tool to hint CJK fonts?

### ISSUE THREAD

**Issue by wangdong1226** [chlorophytum/hm-ideograph#1]
大神！

在网上搜了太多资料如何给CJK字体进行优质且高效的hinting，最后终于找到大神制作的 sfdhanautohint，然后又找到其进化版本的ideohint，这两个工具有说明文档还能知道怎么使用。

再次进化后的新软件 hm-ideograph 实在搜不到完整的使用说明，对于小白来说真不知道如何下手使用。

请大神指点一下，能否写个就像 ideohint 的说明文件那样的使用介绍？

诚挚感谢！再次膜拜！

Davy.

**Comment by be5invis** [comment]
This HM is still highly unstable (the interface may change in the future). I may write some docs about it (and the main engine) if I think it is stable enough...
Resolve as by design (for now).

**Comment by wangdong1226** [comment]
尝试使用大神的这个神器，显示cholrophytum版本为0.40.4。
对衬线字体（比如思源宋体）中大部分字体能够做到完美的hinting，但也发现比如“慧”字体顶部的小横线出现渲染错误的情况：
[https://github.com/wangdong1226/Photo/blob/f0a6d594eb1d309e979deb2d8521925504a4b51d/strokes_LI.jpg](url)
恳请大神看看是什么情况，能否修复一下。感激不尽！

对非衬线字体（比如思源黑体）情况要好一点，但也发现个别笔画复杂的字符，也出现如上渲染错误的情况。
